@startuml
' Diagrama de Secuencia: Creación y Gestión de Efectos
actor Jugador
participant "Personaje" as P
participant "GameFactoryProvider" as GFP
participant "DefaultGameObjectFactory" as Factory
participant "DefaultParticulaFactory" as PF
participant "CoroutineRunner" as CR

Jugador -> P: Dispara
activate P

P -> GFP: Instance.ParticulaFactory
activate GFP
GFP --> P: factory
deactivate GFP

P -> PF: EmitirParticula(pos, rot, 2f)
activate PF

PF -> PF: Instantiate(prefab)
PF -> CR: Run(DestroyAfterDelay)
activate CR
CR --> PF: routine
deactivate CR

PF --> P: particula
deactivate PF

P -> GFP: Instance.ExplosionFactory
activate GFP
GFP --> P: factory
deactivate GFP

P -> Factory: CrearExplosion(pos, rot)
activate Factory
Factory --> P: explosion
deactivate Factory

deactivate P

@enduml